---
abstract: 'Generate a Timecard chart from a time series'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Cukes: 0.05
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.86'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chart-Timecard
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Object::Tiny: 1.06
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.01
